email:
  user: travelplannerpro.official@gmail.com
  password: oosb hvkk rkct rylv
  recipient: y.destiny.spyair@gmail.com
  smtp_server: smtp.gmail.com
  smtp_port: 465

excel:
  input_folder: ./excelデータ
  output_path: ./output/毎月の売上レポート.xlsx
